<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "de_ajaxpost"
 *
 * Auto generated by Extension Builder 2014-10-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ajaxpost',
	'description' => 'Extbase/ Fluid Ajax Example',
	'category' => 'plugin',
	'author' => 'Dirk Eckert',
	'author_email' => 'google@de-velopment.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);